### ISSUE TITLE
Не работает с https в Метро

### ISSUE THREAD

**Issue by apetrin** [thermatk/HSEWifi#7]
Предлагается поснифать ещё раз, и попытаться разгадать их пароли. Возможно нагрепать пару десятков паролей ничего не знающих пользователей, и случайным образом давать их.

**Comment by thermatk** [comment]
В Миланском метро нечего сниффать :)
Предлагаю всем заинтересованным включить monitor mode на wifi-адаптерах и погулять с wireshark'ом, сеть ведь по-прежнему ничем не защищена?
